
### INPUT
cell_clusters: "config/config_cell_clusters.tsv"
model_config: "config/config_models.tsv"

### OUTPUT
results_dir: "results_training/"

### PARAMS
encode_re2g_dir: "ENCODE_rE2G"
run_feature_analysis: True
