
### INPUT
multiome_samples: "config/config_multiome_samples.tsv"
cell_clusters: "config/config_cell_clusters.tsv"
meta_data: "example_chr22_multiome/meta_data.csv"
rna_matrix: "example_chr22_multiome/rna_matrix.csv.gz"

### OUTPUT
results_dir: "results/"

# COLUMN NAME IN META_DATA
meta_data_col:
        cell_name: "cell_name"
        sample: "sample"
        cluster: "cluster"
        barcode: "barcode"

### PARAMS
encode_re2g_dir: "ENCODE_rE2G"
model_dir: "models/"

